// Code generated by internal/genposture from testdata/openapi.json; DO NOT EDIT.

package firezone

// Fields of the "defender" provider.
const (
	// PostureDefenderAgentVersion is the version field "defender.agent_version". Platforms: windows, macos, linux.
	PostureDefenderAgentVersion PostureVersionField = "defender.agent_version"
	// PostureDefenderComputerDNSName is the string field "defender.computer_dns_name". Platforms: windows, macos, linux.
	PostureDefenderComputerDNSName PostureStringField = "defender.computer_dns_name"
	// PostureDefenderDefenderID is the string field "defender.defender_id". Platforms: windows, macos, linux.
	PostureDefenderDefenderID PostureStringField = "defender.defender_id"
	// PostureDefenderDeviceValue is the enum_string field "defender.device_value". Platforms: windows, macos, linux.
	PostureDefenderDeviceValue PostureStringField = "defender.device_value"
	// PostureDefenderEnrolled is the boolean field "defender.enrolled". Platforms: windows, macos, linux.
	PostureDefenderEnrolled PostureBoolField = "defender.enrolled"
	// PostureDefenderEntraDeviceID is the string field "defender.entra_device_id". Platforms: windows, macos, linux.
	PostureDefenderEntraDeviceID PostureStringField = "defender.entra_device_id"
	// PostureDefenderEntraJoined is the boolean field "defender.entra_joined". Platforms: windows, macos, linux.
	PostureDefenderEntraJoined PostureBoolField = "defender.entra_joined"
	// PostureDefenderExclusionReason is the enum_string field "defender.exclusion_reason". Platforms: windows, macos, linux.
	PostureDefenderExclusionReason PostureStringField = "defender.exclusion_reason"
	// PostureDefenderExposureLevel is the enum_string field "defender.exposure_level". Platforms: windows, macos, linux.
	PostureDefenderExposureLevel PostureStringField = "defender.exposure_level"
	// PostureDefenderFirstSeenAt is the datetime field "defender.first_seen_at". Platforms: windows, macos, linux.
	PostureDefenderFirstSeenAt PostureTimestampField = "defender.first_seen_at"
	// PostureDefenderHealthStatus is the enum_string field "defender.health_status". Platforms: windows, macos, linux.
	PostureDefenderHealthStatus PostureStringField = "defender.health_status"
	// PostureDefenderIPAddresses is the json field "defender.ip_addresses". Platforms: windows, macos, linux.
	PostureDefenderIPAddresses PostureJSONField = "defender.ip_addresses"
	// PostureDefenderIsExcluded is the boolean field "defender.is_excluded". Platforms: windows, macos, linux.
	PostureDefenderIsExcluded PostureBoolField = "defender.is_excluded"
	// PostureDefenderIsPotentialDuplication is the boolean field "defender.is_potential_duplication". Platforms: windows, macos, linux.
	PostureDefenderIsPotentialDuplication PostureBoolField = "defender.is_potential_duplication"
	// PostureDefenderLastExternalIPAddress is the ip field "defender.last_external_ip_address". Platforms: windows, macos, linux.
	PostureDefenderLastExternalIPAddress PostureIPField = "defender.last_external_ip_address"
	// PostureDefenderLastIPAddress is the ip field "defender.last_ip_address". Platforms: windows, macos, linux.
	PostureDefenderLastIPAddress PostureIPField = "defender.last_ip_address"
	// PostureDefenderLastSeenAt is the datetime field "defender.last_seen_at". Platforms: windows, macos, linux.
	PostureDefenderLastSeenAt PostureTimestampField = "defender.last_seen_at"
	// PostureDefenderMachineTags is the string_array field "defender.machine_tags". Platforms: windows, macos, linux.
	PostureDefenderMachineTags PostureStringArrayField = "defender.machine_tags"
	// PostureDefenderManagedBy is the enum_string field "defender.managed_by". Platforms: windows, macos, linux.
	PostureDefenderManagedBy PostureStringField = "defender.managed_by"
	// PostureDefenderManagedByStatus is the enum_string field "defender.managed_by_status". Platforms: windows, macos, linux.
	PostureDefenderManagedByStatus PostureStringField = "defender.managed_by_status"
	// PostureDefenderOnboardingStatus is the enum_string field "defender.onboarding_status". Platforms: windows, macos, linux.
	PostureDefenderOnboardingStatus PostureStringField = "defender.onboarding_status"
	// PostureDefenderOSArchitecture is the enum_string field "defender.os_architecture". Platforms: windows, macos, linux.
	PostureDefenderOSArchitecture PostureStringField = "defender.os_architecture"
	// PostureDefenderOSBuild is the integer field "defender.os_build". Platforms: windows, macos, linux.
	PostureDefenderOSBuild PostureIntegerField = "defender.os_build"
	// PostureDefenderOSPlatform is the enum_string field "defender.os_platform". Platforms: windows, macos, linux.
	PostureDefenderOSPlatform PostureStringField = "defender.os_platform"
	// PostureDefenderOSProcessor is the string field "defender.os_processor". Platforms: windows, macos, linux.
	PostureDefenderOSProcessor PostureStringField = "defender.os_processor"
	// PostureDefenderOSUpToDate is the boolean field "defender.os_up_to_date". Platforms: macos.
	PostureDefenderOSUpToDate PostureBoolField = "defender.os_up_to_date"
	// PostureDefenderRBACGroupID is the integer field "defender.rbac_group_id". Platforms: windows, macos, linux.
	PostureDefenderRBACGroupID PostureIntegerField = "defender.rbac_group_id"
	// PostureDefenderRBACGroupName is the string field "defender.rbac_group_name". Platforms: windows, macos, linux.
	PostureDefenderRBACGroupName PostureStringField = "defender.rbac_group_name"
	// PostureDefenderRiskScore is the enum_string field "defender.risk_score". Platforms: windows, macos, linux.
	PostureDefenderRiskScore PostureStringField = "defender.risk_score"
	// PostureDefenderVersion is the string field "defender.version". Platforms: windows, macos, linux.
	PostureDefenderVersion PostureStringField = "defender.version"
	// PostureDefenderVMCloudProvider is the string field "defender.vm_cloud_provider". Platforms: windows, macos, linux.
	PostureDefenderVMCloudProvider PostureStringField = "defender.vm_cloud_provider"
	// PostureDefenderVMID is the string field "defender.vm_id". Platforms: windows, macos, linux.
	PostureDefenderVMID PostureStringField = "defender.vm_id"
	// PostureDefenderVMResourceID is the string field "defender.vm_resource_id". Platforms: windows, macos, linux.
	PostureDefenderVMResourceID PostureStringField = "defender.vm_resource_id"
	// PostureDefenderVMSubscriptionID is the string field "defender.vm_subscription_id". Platforms: windows, macos, linux.
	PostureDefenderVMSubscriptionID PostureStringField = "defender.vm_subscription_id"
)

// Fields of the "firezone" provider.
const (
	// PostureFirezoneDeviceSerial is the string field "firezone.device_serial". Platforms: windows, macos, linux, ios, android.
	PostureFirezoneDeviceSerial PostureStringField = "firezone.device_serial"
	// PostureFirezoneDeviceUUID is the string field "firezone.device_uuid". Platforms: windows, macos, linux, ios, android.
	PostureFirezoneDeviceUUID PostureStringField = "firezone.device_uuid"
	// PostureFirezoneHostname is the string field "firezone.hostname". Platforms: windows, macos, linux, ios, android.
	PostureFirezoneHostname PostureStringField = "firezone.hostname"
	// PostureFirezoneIdentifierForVendor is the string field "firezone.identifier_for_vendor". Platforms: windows, macos, linux, ios, android.
	PostureFirezoneIdentifierForVendor PostureStringField = "firezone.identifier_for_vendor"
	// PostureFirezoneIPv4 is the ipv4 field "firezone.ipv4". Platforms: windows, macos, linux, ios, android.
	PostureFirezoneIPv4 PostureIPField = "firezone.ipv4"
	// PostureFirezoneIPv6 is the ipv6 field "firezone.ipv6". Platforms: windows, macos, linux, ios, android.
	PostureFirezoneIPv6 PostureIPField = "firezone.ipv6"
	// PostureFirezoneLastAttestedAt is the datetime field "firezone.last_attested_at". Platforms: windows, macos, linux, ios, android.
	PostureFirezoneLastAttestedAt PostureTimestampField = "firezone.last_attested_at"
	// PostureFirezoneLastAttestedCertFingerprint is the string field "firezone.last_attested_cert_fingerprint". Platforms: windows, macos, linux, ios, android.
	PostureFirezoneLastAttestedCertFingerprint PostureStringField = "firezone.last_attested_cert_fingerprint"
	// PostureFirezoneLastAttestedCertSerial is the string field "firezone.last_attested_cert_serial". Platforms: windows, macos, linux, ios, android.
	PostureFirezoneLastAttestedCertSerial PostureStringField = "firezone.last_attested_cert_serial"
	// PostureFirezoneLastAttestedDeviceSerial is the string field "firezone.last_attested_device_serial". Platforms: windows, macos, linux, ios, android.
	PostureFirezoneLastAttestedDeviceSerial PostureStringField = "firezone.last_attested_device_serial"
	// PostureFirezoneLastAttestedDeviceUUID is the string field "firezone.last_attested_device_uuid". Platforms: windows, macos, linux, ios, android.
	PostureFirezoneLastAttestedDeviceUUID PostureStringField = "firezone.last_attested_device_uuid"
	// PostureFirezoneLastAttestedMDMDeviceID is the string field "firezone.last_attested_mdm_device_id". Platforms: windows, macos, linux, ios, android.
	PostureFirezoneLastAttestedMDMDeviceID PostureStringField = "firezone.last_attested_mdm_device_id"
	// PostureFirezoneLastSeenRemoteIPLocationCity is the string field "firezone.last_seen_remote_ip_location_city". Platforms: windows, macos, linux, ios, android.
	PostureFirezoneLastSeenRemoteIPLocationCity PostureStringField = "firezone.last_seen_remote_ip_location_city"
	// PostureFirezoneLastSeenUserAgent is the string field "firezone.last_seen_user_agent". Platforms: windows, macos, linux, ios, android.
	PostureFirezoneLastSeenUserAgent PostureStringField = "firezone.last_seen_user_agent"
	// PostureFirezoneLastSeenVersion is the version field "firezone.last_seen_version". Platforms: windows, macos, linux, ios, android.
	PostureFirezoneLastSeenVersion PostureVersionField = "firezone.last_seen_version"
	// PostureFirezoneName is the string field "firezone.name". Platforms: windows, macos, linux, ios, android.
	PostureFirezoneName PostureStringField = "firezone.name"
)

// Fields of the "intune" provider.
const (
	// PostureIntuneAndroidSecurityPatchLevel is the datetime field "intune.android_security_patch_level". Platforms: windows, macos, ios, android.
	PostureIntuneAndroidSecurityPatchLevel PostureTimestampField = "intune.android_security_patch_level"
	// PostureIntuneAttestationBitLockerEnabled is the boolean field "intune.attestation_bit_locker_enabled". Platforms: windows.
	PostureIntuneAttestationBitLockerEnabled PostureBoolField = "intune.attestation_bit_locker_enabled"
	// PostureIntuneAttestationBootAppSecurityVersion is the version field "intune.attestation_boot_app_security_version". Platforms: windows.
	PostureIntuneAttestationBootAppSecurityVersion PostureVersionField = "intune.attestation_boot_app_security_version"
	// PostureIntuneAttestationBootDebugging is the boolean field "intune.attestation_boot_debugging". Platforms: windows.
	PostureIntuneAttestationBootDebugging PostureBoolField = "intune.attestation_boot_debugging"
	// PostureIntuneAttestationBootManagerSecurityVersion is the version field "intune.attestation_boot_manager_security_version". Platforms: windows.
	PostureIntuneAttestationBootManagerSecurityVersion PostureVersionField = "intune.attestation_boot_manager_security_version"
	// PostureIntuneAttestationBootManagerVersion is the version field "intune.attestation_boot_manager_version". Platforms: windows.
	PostureIntuneAttestationBootManagerVersion PostureVersionField = "intune.attestation_boot_manager_version"
	// PostureIntuneAttestationBootRevisionListInfo is the string field "intune.attestation_boot_revision_list_info". Platforms: windows.
	PostureIntuneAttestationBootRevisionListInfo PostureStringField = "intune.attestation_boot_revision_list_info"
	// PostureIntuneAttestationCodeIntegrity is the boolean field "intune.attestation_code_integrity". Platforms: windows.
	PostureIntuneAttestationCodeIntegrity PostureBoolField = "intune.attestation_code_integrity"
	// PostureIntuneAttestationCodeIntegrityCheckVersion is the version field "intune.attestation_code_integrity_check_version". Platforms: windows.
	PostureIntuneAttestationCodeIntegrityCheckVersion PostureVersionField = "intune.attestation_code_integrity_check_version"
	// PostureIntuneAttestationCodeIntegrityPolicy is the string field "intune.attestation_code_integrity_policy". Platforms: windows.
	PostureIntuneAttestationCodeIntegrityPolicy PostureStringField = "intune.attestation_code_integrity_policy"
	// PostureIntuneAttestationContentVersion is the version field "intune.attestation_content_version". Platforms: windows.
	PostureIntuneAttestationContentVersion PostureVersionField = "intune.attestation_content_version"
	// PostureIntuneAttestationDataExecutionPolicyEnabled is the boolean field "intune.attestation_data_execution_policy_enabled". Platforms: windows.
	PostureIntuneAttestationDataExecutionPolicyEnabled PostureBoolField = "intune.attestation_data_execution_policy_enabled"
	// PostureIntuneAttestationEarlyLaunchAntiMalwareDriverProtection is the boolean field "intune.attestation_early_launch_anti_malware_driver_protection". Platforms: windows.
	PostureIntuneAttestationEarlyLaunchAntiMalwareDriverProtection PostureBoolField = "intune.attestation_early_launch_anti_malware_driver_protection"
	// PostureIntuneAttestationHealthStatusMismatchInfo is the string field "intune.attestation_health_status_mismatch_info". Platforms: windows.
	PostureIntuneAttestationHealthStatusMismatchInfo PostureStringField = "intune.attestation_health_status_mismatch_info"
	// PostureIntuneAttestationIdentityKey is the string field "intune.attestation_identity_key". Platforms: windows.
	PostureIntuneAttestationIdentityKey PostureStringField = "intune.attestation_identity_key"
	// PostureIntuneAttestationIssuedAt is the datetime field "intune.attestation_issued_at". Platforms: windows.
	PostureIntuneAttestationIssuedAt PostureTimestampField = "intune.attestation_issued_at"
	// PostureIntuneAttestationOperatingSystemKernelDebugging is the boolean field "intune.attestation_operating_system_kernel_debugging". Platforms: windows.
	PostureIntuneAttestationOperatingSystemKernelDebugging PostureBoolField = "intune.attestation_operating_system_kernel_debugging"
	// PostureIntuneAttestationOperatingSystemRevListInfo is the string field "intune.attestation_operating_system_rev_list_info". Platforms: windows.
	PostureIntuneAttestationOperatingSystemRevListInfo PostureStringField = "intune.attestation_operating_system_rev_list_info"
	// PostureIntuneAttestationPCR0 is the string field "intune.attestation_pcr0". Platforms: windows.
	PostureIntuneAttestationPCR0 PostureStringField = "intune.attestation_pcr0"
	// PostureIntuneAttestationPCRHashAlgorithm is the string field "intune.attestation_pcr_hash_algorithm". Platforms: windows.
	PostureIntuneAttestationPCRHashAlgorithm PostureStringField = "intune.attestation_pcr_hash_algorithm"
	// PostureIntuneAttestationResetCount is the integer field "intune.attestation_reset_count". Platforms: windows.
	PostureIntuneAttestationResetCount PostureIntegerField = "intune.attestation_reset_count"
	// PostureIntuneAttestationRestartCount is the integer field "intune.attestation_restart_count". Platforms: windows.
	PostureIntuneAttestationRestartCount PostureIntegerField = "intune.attestation_restart_count"
	// PostureIntuneAttestationSafeMode is the boolean field "intune.attestation_safe_mode". Platforms: windows.
	PostureIntuneAttestationSafeMode PostureBoolField = "intune.attestation_safe_mode"
	// PostureIntuneAttestationSecureBoot is the boolean field "intune.attestation_secure_boot". Platforms: windows.
	PostureIntuneAttestationSecureBoot PostureBoolField = "intune.attestation_secure_boot"
	// PostureIntuneAttestationSecureBootConfigPolicyFingerprint is the string field "intune.attestation_secure_boot_config_policy_fingerprint". Platforms: windows.
	PostureIntuneAttestationSecureBootConfigPolicyFingerprint PostureStringField = "intune.attestation_secure_boot_config_policy_fingerprint"
	// PostureIntuneAttestationStatus is the enum_string field "intune.attestation_status". Platforms: windows.
	PostureIntuneAttestationStatus PostureStringField = "intune.attestation_status"
	// PostureIntuneAttestationSupported is the boolean field "intune.attestation_supported". Platforms: windows.
	PostureIntuneAttestationSupported PostureBoolField = "intune.attestation_supported"
	// PostureIntuneAttestationTestSigning is the boolean field "intune.attestation_test_signing". Platforms: windows.
	PostureIntuneAttestationTestSigning PostureBoolField = "intune.attestation_test_signing"
	// PostureIntuneAttestationTPMVersion is the version field "intune.attestation_tpm_version". Platforms: windows.
	PostureIntuneAttestationTPMVersion PostureVersionField = "intune.attestation_tpm_version"
	// PostureIntuneAttestationVirtualSecureMode is the boolean field "intune.attestation_virtual_secure_mode". Platforms: windows.
	PostureIntuneAttestationVirtualSecureMode PostureBoolField = "intune.attestation_virtual_secure_mode"
	// PostureIntuneAttestationWindowsPE is the boolean field "intune.attestation_windows_pe". Platforms: windows.
	PostureIntuneAttestationWindowsPE PostureBoolField = "intune.attestation_windows_pe"
	// PostureIntuneComplianceGracePeriodExpirationAt is the datetime field "intune.compliance_grace_period_expiration_at". Platforms: windows, macos, ios, android.
	PostureIntuneComplianceGracePeriodExpirationAt PostureTimestampField = "intune.compliance_grace_period_expiration_at"
	// PostureIntuneComplianceState is the enum_string field "intune.compliance_state". Platforms: windows, macos, ios, android.
	PostureIntuneComplianceState PostureStringField = "intune.compliance_state"
	// PostureIntuneConfigManagerCompliancePolicy is the boolean field "intune.config_manager_compliance_policy". Platforms: windows, macos, ios, android.
	PostureIntuneConfigManagerCompliancePolicy PostureBoolField = "intune.config_manager_compliance_policy"
	// PostureIntuneConfigManagerDeviceConfiguration is the boolean field "intune.config_manager_device_configuration". Platforms: windows, macos, ios, android.
	PostureIntuneConfigManagerDeviceConfiguration PostureBoolField = "intune.config_manager_device_configuration"
	// PostureIntuneConfigManagerInventory is the boolean field "intune.config_manager_inventory". Platforms: windows, macos, ios, android.
	PostureIntuneConfigManagerInventory PostureBoolField = "intune.config_manager_inventory"
	// PostureIntuneConfigManagerModernApps is the boolean field "intune.config_manager_modern_apps". Platforms: windows, macos, ios, android.
	PostureIntuneConfigManagerModernApps PostureBoolField = "intune.config_manager_modern_apps"
	// PostureIntuneConfigManagerResourceAccess is the boolean field "intune.config_manager_resource_access". Platforms: windows, macos, ios, android.
	PostureIntuneConfigManagerResourceAccess PostureBoolField = "intune.config_manager_resource_access"
	// PostureIntuneConfigManagerWindowsUpdateForBusiness is the boolean field "intune.config_manager_windows_update_for_business". Platforms: windows, macos, ios, android.
	PostureIntuneConfigManagerWindowsUpdateForBusiness PostureBoolField = "intune.config_manager_windows_update_for_business"
	// PostureIntuneDeviceCategoryDisplayName is the string field "intune.device_category_display_name". Platforms: windows, macos, ios, android.
	PostureIntuneDeviceCategoryDisplayName PostureStringField = "intune.device_category_display_name"
	// PostureIntuneDeviceEnrollmentType is the enum_string field "intune.device_enrollment_type". Platforms: windows, macos, ios, android.
	PostureIntuneDeviceEnrollmentType PostureStringField = "intune.device_enrollment_type"
	// PostureIntuneDeviceName is the string field "intune.device_name". Platforms: windows, macos, ios, android.
	PostureIntuneDeviceName PostureStringField = "intune.device_name"
	// PostureIntuneDeviceRegistrationState is the enum_string field "intune.device_registration_state". Platforms: windows, macos, ios, android.
	PostureIntuneDeviceRegistrationState PostureStringField = "intune.device_registration_state"
	// PostureIntuneEASActivated is the boolean field "intune.eas_activated". Platforms: windows, macos, ios, android.
	PostureIntuneEASActivated PostureBoolField = "intune.eas_activated"
	// PostureIntuneEASActivatedAt is the datetime field "intune.eas_activated_at". Platforms: windows, macos, ios, android.
	PostureIntuneEASActivatedAt PostureTimestampField = "intune.eas_activated_at"
	// PostureIntuneEASDeviceID is the string field "intune.eas_device_id". Platforms: windows, macos, ios, android.
	PostureIntuneEASDeviceID PostureStringField = "intune.eas_device_id"
	// PostureIntuneEmailAddress is the string field "intune.email_address". Platforms: windows, macos, ios, android.
	PostureIntuneEmailAddress PostureStringField = "intune.email_address"
	// PostureIntuneEnrolled is the boolean field "intune.enrolled". Platforms: windows, macos, ios, android.
	PostureIntuneEnrolled PostureBoolField = "intune.enrolled"
	// PostureIntuneEnrolledAt is the datetime field "intune.enrolled_at". Platforms: windows, macos, ios, android.
	PostureIntuneEnrolledAt PostureTimestampField = "intune.enrolled_at"
	// PostureIntuneEnrollmentProfileName is the string field "intune.enrollment_profile_name". Platforms: windows, macos, ios, android.
	PostureIntuneEnrollmentProfileName PostureStringField = "intune.enrollment_profile_name"
	// PostureIntuneEntraDeviceID is the string field "intune.entra_device_id". Platforms: windows, macos, ios, android.
	PostureIntuneEntraDeviceID PostureStringField = "intune.entra_device_id"
	// PostureIntuneEntraRegistered is the boolean field "intune.entra_registered". Platforms: windows, macos, ios, android.
	PostureIntuneEntraRegistered PostureBoolField = "intune.entra_registered"
	// PostureIntuneEthernetMACAddress is the string field "intune.ethernet_mac_address". Platforms: windows, macos, ios, android.
	PostureIntuneEthernetMACAddress PostureStringField = "intune.ethernet_mac_address"
	// PostureIntuneExchangeAccessState is the enum_string field "intune.exchange_access_state". Platforms: windows, macos, ios, android.
	PostureIntuneExchangeAccessState PostureStringField = "intune.exchange_access_state"
	// PostureIntuneExchangeAccessStateReason is the enum_string field "intune.exchange_access_state_reason". Platforms: windows, macos, ios, android.
	PostureIntuneExchangeAccessStateReason PostureStringField = "intune.exchange_access_state_reason"
	// PostureIntuneExchangeLastSuccessfulSyncAt is the datetime field "intune.exchange_last_successful_sync_at". Platforms: windows, macos, ios, android.
	PostureIntuneExchangeLastSuccessfulSyncAt PostureTimestampField = "intune.exchange_last_successful_sync_at"
	// PostureIntuneFreeStorageSpaceBytes is the integer field "intune.free_storage_space_bytes". Platforms: windows, macos, ios, android.
	PostureIntuneFreeStorageSpaceBytes PostureIntegerField = "intune.free_storage_space_bytes"
	// PostureIntuneICCID is the string field "intune.iccid". Platforms: windows, macos, ios, android.
	PostureIntuneICCID PostureStringField = "intune.iccid"
	// PostureIntuneIMEI is the string field "intune.imei". Platforms: windows, macos, ios, android.
	PostureIntuneIMEI PostureStringField = "intune.imei"
	// PostureIntuneIntuneID is the string field "intune.intune_id". Platforms: windows, macos, ios, android.
	PostureIntuneIntuneID PostureStringField = "intune.intune_id"
	// PostureIntuneIsEncrypted is the boolean field "intune.is_encrypted". Platforms: windows, macos, ios, android.
	PostureIntuneIsEncrypted PostureBoolField = "intune.is_encrypted"
	// PostureIntuneIsSupervised is the boolean field "intune.is_supervised". Platforms: macos, ios.
	PostureIntuneIsSupervised PostureBoolField = "intune.is_supervised"
	// PostureIntuneJailBroken is the boolean field "intune.jail_broken". Platforms: ios, android.
	PostureIntuneJailBroken PostureBoolField = "intune.jail_broken"
	// PostureIntuneLastSyncAt is the datetime field "intune.last_sync_at". Platforms: windows, macos, ios, android.
	PostureIntuneLastSyncAt PostureTimestampField = "intune.last_sync_at"
	// PostureIntuneManagedDeviceName is the string field "intune.managed_device_name". Platforms: windows, macos, ios, android.
	PostureIntuneManagedDeviceName PostureStringField = "intune.managed_device_name"
	// PostureIntuneManagedDeviceOwnerType is the enum_string field "intune.managed_device_owner_type". Platforms: windows, macos, ios, android.
	PostureIntuneManagedDeviceOwnerType PostureStringField = "intune.managed_device_owner_type"
	// PostureIntuneManagementAgent is the enum_string field "intune.management_agent". Platforms: windows, macos, ios, android.
	PostureIntuneManagementAgent PostureStringField = "intune.management_agent"
	// PostureIntuneManagementCertificateExpiresAt is the datetime field "intune.management_certificate_expires_at". Platforms: windows, macos, ios, android.
	PostureIntuneManagementCertificateExpiresAt PostureTimestampField = "intune.management_certificate_expires_at"
	// PostureIntuneManagementState is the enum_string field "intune.management_state". Platforms: windows, macos, ios, android.
	PostureIntuneManagementState PostureStringField = "intune.management_state"
	// PostureIntuneManufacturer is the string field "intune.manufacturer". Platforms: windows, macos, ios, android.
	PostureIntuneManufacturer PostureStringField = "intune.manufacturer"
	// PostureIntuneMEID is the string field "intune.meid". Platforms: windows, macos, ios, android.
	PostureIntuneMEID PostureStringField = "intune.meid"
	// PostureIntuneModel is the string field "intune.model". Platforms: windows, macos, ios, android.
	PostureIntuneModel PostureStringField = "intune.model"
	// PostureIntuneNotes is the string field "intune.notes". Platforms: windows, macos, ios, android.
	PostureIntuneNotes PostureStringField = "intune.notes"
	// PostureIntuneOperatingSystem is the string field "intune.operating_system". Platforms: windows, macos, ios, android.
	PostureIntuneOperatingSystem PostureStringField = "intune.operating_system"
	// PostureIntuneOSUpToDate is the boolean field "intune.os_up_to_date". Platforms: windows, macos, ios, android.
	PostureIntuneOSUpToDate PostureBoolField = "intune.os_up_to_date"
	// PostureIntuneOSVersion is the version field "intune.os_version". Platforms: windows, macos, ios, android.
	PostureIntuneOSVersion PostureVersionField = "intune.os_version"
	// PostureIntunePartnerReportedThreatState is the enum_string field "intune.partner_reported_threat_state". Platforms: windows, macos, ios, android.
	PostureIntunePartnerReportedThreatState PostureStringField = "intune.partner_reported_threat_state"
	// PostureIntunePhoneNumber is the string field "intune.phone_number". Platforms: windows, macos, ios, android.
	PostureIntunePhoneNumber PostureStringField = "intune.phone_number"
	// PostureIntunePhysicalMemoryBytes is the integer field "intune.physical_memory_bytes". Platforms: windows, macos, ios, android.
	PostureIntunePhysicalMemoryBytes PostureIntegerField = "intune.physical_memory_bytes"
	// PostureIntuneRequireUserEnrollmentApproval is the boolean field "intune.require_user_enrollment_approval". Platforms: windows, macos, ios, android.
	PostureIntuneRequireUserEnrollmentApproval PostureBoolField = "intune.require_user_enrollment_approval"
	// PostureIntuneSerialNumber is the string field "intune.serial_number". Platforms: windows, macos, ios, android.
	PostureIntuneSerialNumber PostureStringField = "intune.serial_number"
	// PostureIntuneSubscriberCarrier is the string field "intune.subscriber_carrier". Platforms: windows, macos, ios, android.
	PostureIntuneSubscriberCarrier PostureStringField = "intune.subscriber_carrier"
	// PostureIntuneTotalStorageSpaceBytes is the integer field "intune.total_storage_space_bytes". Platforms: windows, macos, ios, android.
	PostureIntuneTotalStorageSpaceBytes PostureIntegerField = "intune.total_storage_space_bytes"
	// PostureIntuneUDID is the string field "intune.udid". Platforms: windows, macos, ios, android.
	PostureIntuneUDID PostureStringField = "intune.udid"
	// PostureIntuneUserDisplayName is the string field "intune.user_display_name". Platforms: windows, macos, ios, android.
	PostureIntuneUserDisplayName PostureStringField = "intune.user_display_name"
	// PostureIntuneUserID is the string field "intune.user_id". Platforms: windows, macos, ios, android.
	PostureIntuneUserID PostureStringField = "intune.user_id"
	// PostureIntuneUserPrincipalName is the string field "intune.user_principal_name". Platforms: windows, macos, ios, android.
	PostureIntuneUserPrincipalName PostureStringField = "intune.user_principal_name"
	// PostureIntuneWifiMACAddress is the string field "intune.wifi_mac_address". Platforms: windows, macos, ios, android.
	PostureIntuneWifiMACAddress PostureStringField = "intune.wifi_mac_address"
)

// Fields of the "iru" provider.
const (
	// PostureIruActivationLockAllowedWhileSupervised is the boolean field "iru.activation_lock_allowed_while_supervised". Platforms: macos, ios.
	PostureIruActivationLockAllowedWhileSupervised PostureBoolField = "iru.activation_lock_allowed_while_supervised"
	// PostureIruActivationLockBypassCodeFailed is the boolean field "iru.activation_lock_bypass_code_failed". Platforms: macos, ios.
	PostureIruActivationLockBypassCodeFailed PostureBoolField = "iru.activation_lock_bypass_code_failed"
	// PostureIruActivationLockCollectedAt is the datetime field "iru.activation_lock_collected_at". Platforms: macos, ios.
	PostureIruActivationLockCollectedAt PostureTimestampField = "iru.activation_lock_collected_at"
	// PostureIruActivationLockSupported is the boolean field "iru.activation_lock_supported". Platforms: macos, ios.
	PostureIruActivationLockSupported PostureBoolField = "iru.activation_lock_supported"
	// PostureIruAgentInstalled is the boolean field "iru.agent_installed". Platforms: macos, ios.
	PostureIruAgentInstalled PostureBoolField = "iru.agent_installed"
	// PostureIruAgentVersion is the version field "iru.agent_version". Platforms: macos, ios.
	PostureIruAgentVersion PostureVersionField = "iru.agent_version"
	// PostureIruAnySignedOS is the boolean field "iru.any_signed_os". Platforms: macos, ios.
	PostureIruAnySignedOS PostureBoolField = "iru.any_signed_os"
	// PostureIruAppleSilicon is the boolean field "iru.apple_silicon". Platforms: macos, ios.
	PostureIruAppleSilicon PostureBoolField = "iru.apple_silicon"
	// PostureIruAssetTag is the string field "iru.asset_tag". Platforms: macos, ios.
	PostureIruAssetTag PostureStringField = "iru.asset_tag"
	// PostureIruBlueprintID is the string field "iru.blueprint_id". Platforms: macos, ios.
	PostureIruBlueprintID PostureStringField = "iru.blueprint_id"
	// PostureIruBlueprintName is the string field "iru.blueprint_name". Platforms: macos, ios.
	PostureIruBlueprintName PostureStringField = "iru.blueprint_name"
	// PostureIruBootstrapTokenAuth is the boolean field "iru.bootstrap_token_auth". Platforms: macos, ios.
	PostureIruBootstrapTokenAuth PostureBoolField = "iru.bootstrap_token_auth"
	// PostureIruBootstrapTokenEscrowed is the boolean field "iru.bootstrap_token_escrowed". Platforms: macos, ios.
	PostureIruBootstrapTokenEscrowed PostureBoolField = "iru.bootstrap_token_escrowed"
	// PostureIruCellularTechnology is the enum_string field "iru.cellular_technology". Platforms: macos, ios.
	PostureIruCellularTechnology PostureStringField = "iru.cellular_technology"
	// PostureIruDataRoaming is the boolean field "iru.data_roaming". Platforms: macos, ios.
	PostureIruDataRoaming PostureBoolField = "iru.data_roaming"
	// PostureIruDeviceActivationLockEnabled is the boolean field "iru.device_activation_lock_enabled". Platforms: macos, ios.
	PostureIruDeviceActivationLockEnabled PostureBoolField = "iru.device_activation_lock_enabled"
	// PostureIruDeviceCapacityGB is the float field "iru.device_capacity_gb". Platforms: macos, ios.
	PostureIruDeviceCapacityGB PostureFloatField = "iru.device_capacity_gb"
	// PostureIruDeviceFamily is the enum_string field "iru.device_family". Platforms: macos, ios.
	PostureIruDeviceFamily PostureStringField = "iru.device_family"
	// PostureIruDeviceName is the string field "iru.device_name". Platforms: macos, ios.
	PostureIruDeviceName PostureStringField = "iru.device_name"
	// PostureIruDisplayOSVersion is the version field "iru.display_os_version". Platforms: macos, ios.
	PostureIruDisplayOSVersion PostureVersionField = "iru.display_os_version"
	// PostureIruEnrolled is the boolean field "iru.enrolled". Platforms: macos, ios.
	PostureIruEnrolled PostureBoolField = "iru.enrolled"
	// PostureIruExternalBootLevel is the enum_string field "iru.external_boot_level". Platforms: macos.
	PostureIruExternalBootLevel PostureStringField = "iru.external_boot_level"
	// PostureIruFilevaultCollectedAt is the datetime field "iru.filevault_collected_at". Platforms: macos, ios.
	PostureIruFilevaultCollectedAt PostureTimestampField = "iru.filevault_collected_at"
	// PostureIruFilevaultEnabled is the boolean field "iru.filevault_enabled". Platforms: macos.
	PostureIruFilevaultEnabled PostureBoolField = "iru.filevault_enabled"
	// PostureIruFilevaultKeyEscrowed is the boolean field "iru.filevault_key_escrowed". Platforms: macos, ios.
	PostureIruFilevaultKeyEscrowed PostureBoolField = "iru.filevault_key_escrowed"
	// PostureIruFilevaultKeyRotationScheduledAt is the datetime field "iru.filevault_key_rotation_scheduled_at". Platforms: macos, ios.
	PostureIruFilevaultKeyRotationScheduledAt PostureTimestampField = "iru.filevault_key_rotation_scheduled_at"
	// PostureIruFilevaultKeyType is the enum_string field "iru.filevault_key_type". Platforms: macos.
	PostureIruFilevaultKeyType PostureStringField = "iru.filevault_key_type"
	// PostureIruFilevaultRegenerationNeeded is the boolean field "iru.filevault_regeneration_needed". Platforms: macos, ios.
	PostureIruFilevaultRegenerationNeeded PostureBoolField = "iru.filevault_regeneration_needed"
	// PostureIruFirewallAllowSignedApplications is the boolean field "iru.firewall_allow_signed_applications". Platforms: macos, ios.
	PostureIruFirewallAllowSignedApplications PostureBoolField = "iru.firewall_allow_signed_applications"
	// PostureIruFirewallBlockAllIncoming is the boolean field "iru.firewall_block_all_incoming". Platforms: macos, ios.
	PostureIruFirewallBlockAllIncoming PostureBoolField = "iru.firewall_block_all_incoming"
	// PostureIruFirewallCollectedAt is the datetime field "iru.firewall_collected_at". Platforms: macos, ios.
	PostureIruFirewallCollectedAt PostureTimestampField = "iru.firewall_collected_at"
	// PostureIruFirewallEnabled is the boolean field "iru.firewall_enabled". Platforms: macos.
	PostureIruFirewallEnabled PostureBoolField = "iru.firewall_enabled"
	// PostureIruFirewallLogging is the boolean field "iru.firewall_logging". Platforms: macos, ios.
	PostureIruFirewallLogging PostureBoolField = "iru.firewall_logging"
	// PostureIruFirewallLoggingOption is the enum_string field "iru.firewall_logging_option". Platforms: macos.
	PostureIruFirewallLoggingOption PostureStringField = "iru.firewall_logging_option"
	// PostureIruFirewallStealthMode is the boolean field "iru.firewall_stealth_mode". Platforms: macos, ios.
	PostureIruFirewallStealthMode PostureBoolField = "iru.firewall_stealth_mode"
	// PostureIruFirewallUnloading is the boolean field "iru.firewall_unloading". Platforms: macos, ios.
	PostureIruFirewallUnloading PostureBoolField = "iru.firewall_unloading"
	// PostureIruFirewallVersion is the version field "iru.firewall_version". Platforms: macos.
	PostureIruFirewallVersion PostureVersionField = "iru.firewall_version"
	// PostureIruFirstEnrolledAt is the datetime field "iru.first_enrolled_at". Platforms: macos, ios.
	PostureIruFirstEnrolledAt PostureTimestampField = "iru.first_enrolled_at"
	// PostureIruGatekeeperCollectedAt is the datetime field "iru.gatekeeper_collected_at". Platforms: macos, ios.
	PostureIruGatekeeperCollectedAt PostureTimestampField = "iru.gatekeeper_collected_at"
	// PostureIruGatekeeperEnabled is the boolean field "iru.gatekeeper_enabled". Platforms: macos.
	PostureIruGatekeeperEnabled PostureBoolField = "iru.gatekeeper_enabled"
	// PostureIruGatekeeperOpaqueVersion is the version field "iru.gatekeeper_opaque_version". Platforms: macos.
	PostureIruGatekeeperOpaqueVersion PostureVersionField = "iru.gatekeeper_opaque_version"
	// PostureIruGatekeeperTrustedDevelopers is the boolean field "iru.gatekeeper_trusted_developers". Platforms: macos, ios.
	PostureIruGatekeeperTrustedDevelopers PostureBoolField = "iru.gatekeeper_trusted_developers"
	// PostureIruGatekeeperVersion is the version field "iru.gatekeeper_version". Platforms: macos.
	PostureIruGatekeeperVersion PostureVersionField = "iru.gatekeeper_version"
	// PostureIruHostName is the string field "iru.host_name". Platforms: macos, ios.
	PostureIruHostName PostureStringField = "iru.host_name"
	// PostureIruHotspot is the boolean field "iru.hotspot". Platforms: macos, ios.
	PostureIruHotspot PostureBoolField = "iru.hotspot"
	// PostureIruInventoryCollectedAt is the datetime field "iru.inventory_collected_at". Platforms: macos, ios.
	PostureIruInventoryCollectedAt PostureTimestampField = "iru.inventory_collected_at"
	// PostureIruIruID is the string field "iru.iru_id". Platforms: macos, ios.
	PostureIruIruID PostureStringField = "iru.iru_id"
	// PostureIruIsMissing is the boolean field "iru.is_missing". Platforms: macos, ios.
	PostureIruIsMissing PostureBoolField = "iru.is_missing"
	// PostureIruIsRemoved is the boolean field "iru.is_removed". Platforms: macos, ios.
	PostureIruIsRemoved PostureBoolField = "iru.is_removed"
	// PostureIruKextRequiresBootstrapToken is the boolean field "iru.kext_requires_bootstrap_token". Platforms: macos, ios.
	PostureIruKextRequiresBootstrapToken PostureBoolField = "iru.kext_requires_bootstrap_token"
	// PostureIruLastCheckInAt is the datetime field "iru.last_check_in_at". Platforms: macos, ios.
	PostureIruLastCheckInAt PostureTimestampField = "iru.last_check_in_at"
	// PostureIruLastEnrolledAt is the datetime field "iru.last_enrolled_at". Platforms: macos, ios.
	PostureIruLastEnrolledAt PostureTimestampField = "iru.last_enrolled_at"
	// PostureIruLocalHostname is the string field "iru.local_hostname". Platforms: macos, ios.
	PostureIruLocalHostname PostureStringField = "iru.local_hostname"
	// PostureIruLostModeStatus is the enum_string field "iru.lost_mode_status". Platforms: macos, ios.
	PostureIruLostModeStatus PostureStringField = "iru.lost_mode_status"
	// PostureIruMalwareRemovalToolVersion is the version field "iru.malware_removal_tool_version". Platforms: macos.
	PostureIruMalwareRemovalToolVersion PostureVersionField = "iru.malware_removal_tool_version"
	// PostureIruMDMEnabled is the boolean field "iru.mdm_enabled". Platforms: macos, ios.
	PostureIruMDMEnabled PostureBoolField = "iru.mdm_enabled"
	// PostureIruMDMManagesKext is the boolean field "iru.mdm_manages_kext". Platforms: macos, ios.
	PostureIruMDMManagesKext PostureBoolField = "iru.mdm_manages_kext"
	// PostureIruModel is the string field "iru.model". Platforms: macos, ios.
	PostureIruModel PostureStringField = "iru.model"
	// PostureIruModelIdentifier is the string field "iru.model_identifier". Platforms: macos, ios.
	PostureIruModelIdentifier PostureStringField = "iru.model_identifier"
	// PostureIruModelName is the string field "iru.model_name". Platforms: macos, ios.
	PostureIruModelName PostureStringField = "iru.model_name"
	// PostureIruOSBuild is the string field "iru.os_build". Platforms: macos, ios.
	PostureIruOSBuild PostureStringField = "iru.os_build"
	// PostureIruOSName is the string field "iru.os_name". Platforms: macos, ios.
	PostureIruOSName PostureStringField = "iru.os_name"
	// PostureIruOSUpToDate is the boolean field "iru.os_up_to_date". Platforms: macos, ios.
	PostureIruOSUpToDate PostureBoolField = "iru.os_up_to_date"
	// PostureIruOSVersion is the version field "iru.os_version". Platforms: macos, ios.
	PostureIruOSVersion PostureVersionField = "iru.os_version"
	// PostureIruPlatform is the enum_string field "iru.platform". Platforms: macos, ios.
	PostureIruPlatform PostureStringField = "iru.platform"
	// PostureIruSecureBootLevel is the enum_string field "iru.secure_boot_level". Platforms: macos.
	PostureIruSecureBootLevel PostureStringField = "iru.secure_boot_level"
	// PostureIruSerialNumber is the string field "iru.serial_number". Platforms: macos, ios.
	PostureIruSerialNumber PostureStringField = "iru.serial_number"
	// PostureIruSharedIpad is the boolean field "iru.shared_ipad". Platforms: macos, ios.
	PostureIruSharedIpad PostureBoolField = "iru.shared_ipad"
	// PostureIruSIPEnabled is the boolean field "iru.sip_enabled". Platforms: macos.
	PostureIruSIPEnabled PostureBoolField = "iru.sip_enabled"
	// PostureIruSoftwareUpdateRequiresBootstrapToken is the boolean field "iru.software_update_requires_bootstrap_token". Platforms: macos, ios.
	PostureIruSoftwareUpdateRequiresBootstrapToken PostureBoolField = "iru.software_update_requires_bootstrap_token"
	// PostureIruSSVEnabled is the boolean field "iru.ssv_enabled". Platforms: macos.
	PostureIruSSVEnabled PostureBoolField = "iru.ssv_enabled"
	// PostureIruStartupSettingsCollectedAt is the datetime field "iru.startup_settings_collected_at". Platforms: macos, ios.
	PostureIruStartupSettingsCollectedAt PostureTimestampField = "iru.startup_settings_collected_at"
	// PostureIruSupplementalBuildVersion is the string field "iru.supplemental_build_version". Platforms: macos, ios.
	PostureIruSupplementalBuildVersion PostureStringField = "iru.supplemental_build_version"
	// PostureIruSupplementalOSVersionExtra is the version field "iru.supplemental_os_version_extra". Platforms: macos, ios.
	PostureIruSupplementalOSVersionExtra PostureVersionField = "iru.supplemental_os_version_extra"
	// PostureIruTags is the string_array field "iru.tags". Platforms: macos, ios.
	PostureIruTags PostureStringArrayField = "iru.tags"
	// PostureIruUserActivationLockEnabled is the boolean field "iru.user_activation_lock_enabled". Platforms: macos, ios.
	PostureIruUserActivationLockEnabled PostureBoolField = "iru.user_activation_lock_enabled"
	// PostureIruUserEmail is the string field "iru.user_email". Platforms: macos, ios.
	PostureIruUserEmail PostureStringField = "iru.user_email"
	// PostureIruUserID is the string field "iru.user_id". Platforms: macos, ios.
	PostureIruUserID PostureStringField = "iru.user_id"
	// PostureIruUserIsArchived is the boolean field "iru.user_is_archived". Platforms: macos, ios.
	PostureIruUserIsArchived PostureBoolField = "iru.user_is_archived"
	// PostureIruUserManagesKext is the boolean field "iru.user_manages_kext". Platforms: macos, ios.
	PostureIruUserManagesKext PostureBoolField = "iru.user_manages_kext"
	// PostureIruUserName is the string field "iru.user_name". Platforms: macos, ios.
	PostureIruUserName PostureStringField = "iru.user_name"
	// PostureIruXprotectVersion is the version field "iru.xprotect_version". Platforms: macos.
	PostureIruXprotectVersion PostureVersionField = "iru.xprotect_version"
)

// Fields of the "santa" provider.
const (
	// PostureSantaConfiguredClientMode is the enum_string field "santa.configured_client_mode". Platforms: macos.
	PostureSantaConfiguredClientMode PostureStringField = "santa.configured_client_mode"
	// PostureSantaEnrolled is the boolean field "santa.enrolled". Platforms: macos.
	PostureSantaEnrolled PostureBoolField = "santa.enrolled"
	// PostureSantaFirstSeenAt is the datetime field "santa.first_seen_at". Platforms: macos.
	PostureSantaFirstSeenAt PostureTimestampField = "santa.first_seen_at"
	// PostureSantaHostname is the string field "santa.hostname". Platforms: macos.
	PostureSantaHostname PostureStringField = "santa.hostname"
	// PostureSantaLastPreflightAt is the datetime field "santa.last_preflight_at". Platforms: macos.
	PostureSantaLastPreflightAt PostureTimestampField = "santa.last_preflight_at"
	// PostureSantaLastPreflightIP is the ip field "santa.last_preflight_ip". Platforms: macos.
	PostureSantaLastPreflightIP PostureIPField = "santa.last_preflight_ip"
	// PostureSantaLastSeenClientMode is the enum_string field "santa.last_seen_client_mode". Platforms: macos.
	PostureSantaLastSeenClientMode PostureStringField = "santa.last_seen_client_mode"
	// PostureSantaLastSyncAt is the datetime field "santa.last_sync_at". Platforms: macos.
	PostureSantaLastSyncAt PostureTimestampField = "santa.last_sync_at"
	// PostureSantaMachineModel is the string field "santa.machine_model". Platforms: macos.
	PostureSantaMachineModel PostureStringField = "santa.machine_model"
	// PostureSantaOSBuild is the string field "santa.os_build". Platforms: macos.
	PostureSantaOSBuild PostureStringField = "santa.os_build"
	// PostureSantaOSType is the enum_string field "santa.os_type". Platforms: macos.
	PostureSantaOSType PostureStringField = "santa.os_type"
	// PostureSantaOSUpToDate is the boolean field "santa.os_up_to_date". Platforms: macos.
	PostureSantaOSUpToDate PostureBoolField = "santa.os_up_to_date"
	// PostureSantaOSVersion is the version field "santa.os_version". Platforms: macos.
	PostureSantaOSVersion PostureVersionField = "santa.os_version"
	// PostureSantaPrimaryUser is the string field "santa.primary_user". Platforms: macos.
	PostureSantaPrimaryUser PostureStringField = "santa.primary_user"
	// PostureSantaPrimaryUserGroups is the string_array field "santa.primary_user_groups". Platforms: macos.
	PostureSantaPrimaryUserGroups PostureStringArrayField = "santa.primary_user_groups"
	// PostureSantaRuleSyncAt is the datetime field "santa.rule_sync_at". Platforms: macos.
	PostureSantaRuleSyncAt PostureTimestampField = "santa.rule_sync_at"
	// PostureSantaSantaID is the string field "santa.santa_id". Platforms: macos.
	PostureSantaSantaID PostureStringField = "santa.santa_id"
	// PostureSantaSantaVersion is the version field "santa.santa_version". Platforms: macos.
	PostureSantaSantaVersion PostureVersionField = "santa.santa_version"
	// PostureSantaSantanetdVersion is the version field "santa.santanetd_version". Platforms: macos.
	PostureSantaSantanetdVersion PostureVersionField = "santa.santanetd_version"
	// PostureSantaSerialNumber is the string field "santa.serial_number". Platforms: macos.
	PostureSantaSerialNumber PostureStringField = "santa.serial_number"
	// PostureSantaSIPStatus is the integer field "santa.sip_status". Platforms: macos.
	PostureSantaSIPStatus PostureIntegerField = "santa.sip_status"
	// PostureSantaTags is the string_array field "santa.tags". Platforms: macos.
	PostureSantaTags PostureStringArrayField = "santa.tags"
	// PostureSantaTemporaryAdminModeEndsAt is the datetime field "santa.temporary_admin_mode_ends_at". Platforms: macos.
	PostureSantaTemporaryAdminModeEndsAt PostureTimestampField = "santa.temporary_admin_mode_ends_at"
	// PostureSantaTemporaryAdminModeUser is the string field "santa.temporary_admin_mode_user". Platforms: macos.
	PostureSantaTemporaryAdminModeUser PostureStringField = "santa.temporary_admin_mode_user"
	// PostureSantaTemporaryMonitorModeEndsAt is the datetime field "santa.temporary_monitor_mode_ends_at". Platforms: macos.
	PostureSantaTemporaryMonitorModeEndsAt PostureTimestampField = "santa.temporary_monitor_mode_ends_at"
)

// Fields of the "sentinelone" provider.
const (
	// PostureSentinelOneAccountName is the string field "sentinelone.account_name". Platforms: windows, macos, linux.
	PostureSentinelOneAccountName PostureStringField = "sentinelone.account_name"
	// PostureSentinelOneActiveProtection is the string_array field "sentinelone.active_protection". Platforms: windows, macos, linux.
	PostureSentinelOneActiveProtection PostureStringArrayField = "sentinelone.active_protection"
	// PostureSentinelOneActiveThreats is the integer field "sentinelone.active_threats". Platforms: windows, macos, linux.
	PostureSentinelOneActiveThreats PostureIntegerField = "sentinelone.active_threats"
	// PostureSentinelOneADComputerDistinguishedName is the string field "sentinelone.ad_computer_distinguished_name". Platforms: windows, macos, linux.
	PostureSentinelOneADComputerDistinguishedName PostureStringField = "sentinelone.ad_computer_distinguished_name"
	// PostureSentinelOneADComputerMemberOf is the string_array field "sentinelone.ad_computer_member_of". Platforms: windows, macos, linux.
	PostureSentinelOneADComputerMemberOf PostureStringArrayField = "sentinelone.ad_computer_member_of"
	// PostureSentinelOneADLastUserDistinguishedName is the string field "sentinelone.ad_last_user_distinguished_name". Platforms: windows, macos, linux.
	PostureSentinelOneADLastUserDistinguishedName PostureStringField = "sentinelone.ad_last_user_distinguished_name"
	// PostureSentinelOneADLastUserMemberOf is the string_array field "sentinelone.ad_last_user_member_of". Platforms: windows, macos, linux.
	PostureSentinelOneADLastUserMemberOf PostureStringArrayField = "sentinelone.ad_last_user_member_of"
	// PostureSentinelOneADMail is the string field "sentinelone.ad_mail". Platforms: windows, macos, linux.
	PostureSentinelOneADMail PostureStringField = "sentinelone.ad_mail"
	// PostureSentinelOneADUserPrincipalName is the string field "sentinelone.ad_user_principal_name". Platforms: windows, macos, linux.
	PostureSentinelOneADUserPrincipalName PostureStringField = "sentinelone.ad_user_principal_name"
	// PostureSentinelOneAgentVersion is the version field "sentinelone.agent_version". Platforms: windows, macos, linux.
	PostureSentinelOneAgentVersion PostureVersionField = "sentinelone.agent_version"
	// PostureSentinelOneAllowRemoteShell is the boolean field "sentinelone.allow_remote_shell". Platforms: windows, macos, linux.
	PostureSentinelOneAllowRemoteShell PostureBoolField = "sentinelone.allow_remote_shell"
	// PostureSentinelOneAppsVulnerabilityStatus is the enum_string field "sentinelone.apps_vulnerability_status". Platforms: windows, macos, linux.
	PostureSentinelOneAppsVulnerabilityStatus PostureStringField = "sentinelone.apps_vulnerability_status"
	// PostureSentinelOneCloudProviders is the json field "sentinelone.cloud_providers". Platforms: windows, macos, linux.
	PostureSentinelOneCloudProviders PostureJSONField = "sentinelone.cloud_providers"
	// PostureSentinelOneComputerName is the string field "sentinelone.computer_name". Platforms: windows, macos, linux.
	PostureSentinelOneComputerName PostureStringField = "sentinelone.computer_name"
	// PostureSentinelOneConsoleMigrationStatus is the enum_string field "sentinelone.console_migration_status". Platforms: windows, macos, linux.
	PostureSentinelOneConsoleMigrationStatus PostureStringField = "sentinelone.console_migration_status"
	// PostureSentinelOneCoreCount is the integer field "sentinelone.core_count". Platforms: windows, macos, linux.
	PostureSentinelOneCoreCount PostureIntegerField = "sentinelone.core_count"
	// PostureSentinelOneCPUCount is the integer field "sentinelone.cpu_count". Platforms: windows, macos, linux.
	PostureSentinelOneCPUCount PostureIntegerField = "sentinelone.cpu_count"
	// PostureSentinelOneCPUID is the string field "sentinelone.cpu_id". Platforms: windows, macos, linux.
	PostureSentinelOneCPUID PostureStringField = "sentinelone.cpu_id"
	// PostureSentinelOneDetectionState is the enum_string field "sentinelone.detection_state". Platforms: windows, macos, linux.
	PostureSentinelOneDetectionState PostureStringField = "sentinelone.detection_state"
	// PostureSentinelOneDomain is the string field "sentinelone.domain". Platforms: windows, macos, linux.
	PostureSentinelOneDomain PostureStringField = "sentinelone.domain"
	// PostureSentinelOneEncryptedApplications is the boolean field "sentinelone.encrypted_applications". Platforms: windows, macos, linux.
	PostureSentinelOneEncryptedApplications PostureBoolField = "sentinelone.encrypted_applications"
	// PostureSentinelOneEnrolled is the boolean field "sentinelone.enrolled". Platforms: windows, macos, linux.
	PostureSentinelOneEnrolled PostureBoolField = "sentinelone.enrolled"
	// PostureSentinelOneExternalID is the string field "sentinelone.external_id". Platforms: windows, macos, linux.
	PostureSentinelOneExternalID PostureStringField = "sentinelone.external_id"
	// PostureSentinelOneExternalIP is the ip field "sentinelone.external_ip". Platforms: windows, macos, linux.
	PostureSentinelOneExternalIP PostureIPField = "sentinelone.external_ip"
	// PostureSentinelOneFirewallEnabled is the boolean field "sentinelone.firewall_enabled". Platforms: windows, macos, linux.
	PostureSentinelOneFirewallEnabled PostureBoolField = "sentinelone.firewall_enabled"
	// PostureSentinelOneFirstFullModeAt is the datetime field "sentinelone.first_full_mode_at". Platforms: windows, macos, linux.
	PostureSentinelOneFirstFullModeAt PostureTimestampField = "sentinelone.first_full_mode_at"
	// PostureSentinelOneFullDiskScanUpdatedAt is the datetime field "sentinelone.full_disk_scan_updated_at". Platforms: windows, macos, linux.
	PostureSentinelOneFullDiskScanUpdatedAt PostureTimestampField = "sentinelone.full_disk_scan_updated_at"
	// PostureSentinelOneGroupID is the string field "sentinelone.group_id". Platforms: windows, macos, linux.
	PostureSentinelOneGroupID PostureStringField = "sentinelone.group_id"
	// PostureSentinelOneGroupIP is the string field "sentinelone.group_ip". Platforms: windows, macos, linux.
	PostureSentinelOneGroupIP PostureStringField = "sentinelone.group_ip"
	// PostureSentinelOneGroupName is the string field "sentinelone.group_name". Platforms: windows, macos, linux.
	PostureSentinelOneGroupName PostureStringField = "sentinelone.group_name"
	// PostureSentinelOneHasContainerizedWorkload is the boolean field "sentinelone.has_containerized_workload". Platforms: windows, macos, linux.
	PostureSentinelOneHasContainerizedWorkload PostureBoolField = "sentinelone.has_containerized_workload"
	// PostureSentinelOneInRemoteShellSession is the boolean field "sentinelone.in_remote_shell_session". Platforms: windows, macos, linux.
	PostureSentinelOneInRemoteShellSession PostureBoolField = "sentinelone.in_remote_shell_session"
	// PostureSentinelOneInfected is the boolean field "sentinelone.infected". Platforms: windows, macos, linux.
	PostureSentinelOneInfected PostureBoolField = "sentinelone.infected"
	// PostureSentinelOneInstallerType is the enum_string field "sentinelone.installer_type". Platforms: windows, macos, linux.
	PostureSentinelOneInstallerType PostureStringField = "sentinelone.installer_type"
	// PostureSentinelOneIsActive is the boolean field "sentinelone.is_active". Platforms: windows, macos, linux.
	PostureSentinelOneIsActive PostureBoolField = "sentinelone.is_active"
	// PostureSentinelOneIsADConnector is the boolean field "sentinelone.is_ad_connector". Platforms: windows, macos, linux.
	PostureSentinelOneIsADConnector PostureBoolField = "sentinelone.is_ad_connector"
	// PostureSentinelOneIsDecommissioned is the boolean field "sentinelone.is_decommissioned". Platforms: windows, macos, linux.
	PostureSentinelOneIsDecommissioned PostureBoolField = "sentinelone.is_decommissioned"
	// PostureSentinelOneIsHyperAutomate is the boolean field "sentinelone.is_hyper_automate". Platforms: windows, macos, linux.
	PostureSentinelOneIsHyperAutomate PostureBoolField = "sentinelone.is_hyper_automate"
	// PostureSentinelOneIsPendingUninstall is the boolean field "sentinelone.is_pending_uninstall". Platforms: windows, macos, linux.
	PostureSentinelOneIsPendingUninstall PostureBoolField = "sentinelone.is_pending_uninstall"
	// PostureSentinelOneIsUninstalled is the boolean field "sentinelone.is_uninstalled". Platforms: windows, macos, linux.
	PostureSentinelOneIsUninstalled PostureBoolField = "sentinelone.is_uninstalled"
	// PostureSentinelOneIsUpToDate is the boolean field "sentinelone.is_up_to_date". Platforms: windows, macos, linux.
	PostureSentinelOneIsUpToDate PostureBoolField = "sentinelone.is_up_to_date"
	// PostureSentinelOneLastActiveAt is the datetime field "sentinelone.last_active_at". Platforms: windows, macos, linux.
	PostureSentinelOneLastActiveAt PostureTimestampField = "sentinelone.last_active_at"
	// PostureSentinelOneLastIPToManagement is the ip field "sentinelone.last_ip_to_management". Platforms: windows, macos, linux.
	PostureSentinelOneLastIPToManagement PostureIPField = "sentinelone.last_ip_to_management"
	// PostureSentinelOneLastLoggedInUserName is the string field "sentinelone.last_logged_in_user_name". Platforms: windows, macos, linux.
	PostureSentinelOneLastLoggedInUserName PostureStringField = "sentinelone.last_logged_in_user_name"
	// PostureSentinelOneLastSuccessfulScanAt is the datetime field "sentinelone.last_successful_scan_at". Platforms: windows, macos, linux.
	PostureSentinelOneLastSuccessfulScanAt PostureTimestampField = "sentinelone.last_successful_scan_at"
	// PostureSentinelOneLocationEnabled is the boolean field "sentinelone.location_enabled". Platforms: windows, macos, linux.
	PostureSentinelOneLocationEnabled PostureBoolField = "sentinelone.location_enabled"
	// PostureSentinelOneLocationType is the enum_string field "sentinelone.location_type". Platforms: windows, macos, linux.
	PostureSentinelOneLocationType PostureStringField = "sentinelone.location_type"
	// PostureSentinelOneLocations is the json field "sentinelone.locations". Platforms: windows, macos, linux.
	PostureSentinelOneLocations PostureJSONField = "sentinelone.locations"
	// PostureSentinelOneMachineSID is the string field "sentinelone.machine_sid". Platforms: windows, macos, linux.
	PostureSentinelOneMachineSID PostureStringField = "sentinelone.machine_sid"
	// PostureSentinelOneMachineType is the enum_string field "sentinelone.machine_type". Platforms: windows, macos, linux.
	PostureSentinelOneMachineType PostureStringField = "sentinelone.machine_type"
	// PostureSentinelOneMissingPermissions is the string_array field "sentinelone.missing_permissions". Platforms: windows, macos, linux.
	PostureSentinelOneMissingPermissions PostureStringArrayField = "sentinelone.missing_permissions"
	// PostureSentinelOneMitigationMode is the enum_string field "sentinelone.mitigation_mode". Platforms: windows, macos, linux.
	PostureSentinelOneMitigationMode PostureStringField = "sentinelone.mitigation_mode"
	// PostureSentinelOneMitigationModeSuspicious is the enum_string field "sentinelone.mitigation_mode_suspicious". Platforms: windows, macos, linux.
	PostureSentinelOneMitigationModeSuspicious PostureStringField = "sentinelone.mitigation_mode_suspicious"
	// PostureSentinelOneModelName is the string field "sentinelone.model_name". Platforms: windows, macos, linux.
	PostureSentinelOneModelName PostureStringField = "sentinelone.model_name"
	// PostureSentinelOneNetworkInterfaces is the json field "sentinelone.network_interfaces". Platforms: windows, macos, linux.
	PostureSentinelOneNetworkInterfaces PostureJSONField = "sentinelone.network_interfaces"
	// PostureSentinelOneNetworkQuarantineEnabled is the boolean field "sentinelone.network_quarantine_enabled". Platforms: windows, macos, linux.
	PostureSentinelOneNetworkQuarantineEnabled PostureBoolField = "sentinelone.network_quarantine_enabled"
	// PostureSentinelOneNetworkStatus is the enum_string field "sentinelone.network_status". Platforms: windows, macos, linux.
	PostureSentinelOneNetworkStatus PostureStringField = "sentinelone.network_status"
	// PostureSentinelOneOperationalState is the enum_string field "sentinelone.operational_state". Platforms: windows, macos, linux.
	PostureSentinelOneOperationalState PostureStringField = "sentinelone.operational_state"
	// PostureSentinelOneOperationalStateExpiresAt is the datetime field "sentinelone.operational_state_expires_at". Platforms: windows, macos, linux.
	PostureSentinelOneOperationalStateExpiresAt PostureTimestampField = "sentinelone.operational_state_expires_at"
	// PostureSentinelOneOSArch is the enum_string field "sentinelone.os_arch". Platforms: windows, macos, linux.
	PostureSentinelOneOSArch PostureStringField = "sentinelone.os_arch"
	// PostureSentinelOneOSName is the string field "sentinelone.os_name". Platforms: windows, macos, linux.
	PostureSentinelOneOSName PostureStringField = "sentinelone.os_name"
	// PostureSentinelOneOSRevision is the version field "sentinelone.os_revision". Platforms: windows, macos, linux.
	PostureSentinelOneOSRevision PostureVersionField = "sentinelone.os_revision"
	// PostureSentinelOneOSStartTime is the datetime field "sentinelone.os_start_time". Platforms: windows, macos, linux.
	PostureSentinelOneOSStartTime PostureTimestampField = "sentinelone.os_start_time"
	// PostureSentinelOneOSType is the enum_string field "sentinelone.os_type". Platforms: windows, macos, linux.
	PostureSentinelOneOSType PostureStringField = "sentinelone.os_type"
	// PostureSentinelOneOSUpToDate is the boolean field "sentinelone.os_up_to_date". Platforms: windows, macos.
	PostureSentinelOneOSUpToDate PostureBoolField = "sentinelone.os_up_to_date"
	// PostureSentinelOneOSUsername is the string field "sentinelone.os_username". Platforms: windows, macos, linux.
	PostureSentinelOneOSUsername PostureStringField = "sentinelone.os_username"
	// PostureSentinelOneProtectedContainersCount is the integer field "sentinelone.protected_containers_count". Platforms: windows, macos, linux.
	PostureSentinelOneProtectedContainersCount PostureIntegerField = "sentinelone.protected_containers_count"
	// PostureSentinelOneProtectedPodsCount is the integer field "sentinelone.protected_pods_count". Platforms: windows, macos, linux.
	PostureSentinelOneProtectedPodsCount PostureIntegerField = "sentinelone.protected_pods_count"
	// PostureSentinelOneProtectedTasksCount is the integer field "sentinelone.protected_tasks_count". Platforms: windows, macos, linux.
	PostureSentinelOneProtectedTasksCount PostureIntegerField = "sentinelone.protected_tasks_count"
	// PostureSentinelOneProxyConsole is the boolean field "sentinelone.proxy_console". Platforms: windows, macos, linux.
	PostureSentinelOneProxyConsole PostureBoolField = "sentinelone.proxy_console"
	// PostureSentinelOneProxyDeepVisibility is the boolean field "sentinelone.proxy_deep_visibility". Platforms: windows, macos, linux.
	PostureSentinelOneProxyDeepVisibility PostureBoolField = "sentinelone.proxy_deep_visibility"
	// PostureSentinelOneProxyMethod is the enum_string field "sentinelone.proxy_method". Platforms: windows, macos, linux.
	PostureSentinelOneProxyMethod PostureStringField = "sentinelone.proxy_method"
	// PostureSentinelOneProxyPACFileUsage is the boolean field "sentinelone.proxy_pac_file_usage". Platforms: windows, macos, linux.
	PostureSentinelOneProxyPACFileUsage PostureBoolField = "sentinelone.proxy_pac_file_usage"
	// PostureSentinelOneRangerStatus is the enum_string field "sentinelone.ranger_status". Platforms: windows, macos, linux.
	PostureSentinelOneRangerStatus PostureStringField = "sentinelone.ranger_status"
	// PostureSentinelOneRangerVersion is the version field "sentinelone.ranger_version". Platforms: windows, macos, linux.
	PostureSentinelOneRangerVersion PostureVersionField = "sentinelone.ranger_version"
	// PostureSentinelOneRegisteredAt is the datetime field "sentinelone.registered_at". Platforms: windows, macos, linux.
	PostureSentinelOneRegisteredAt PostureTimestampField = "sentinelone.registered_at"
	// PostureSentinelOneRemoteProfilingState is the enum_string field "sentinelone.remote_profiling_state". Platforms: windows, macos, linux.
	PostureSentinelOneRemoteProfilingState PostureStringField = "sentinelone.remote_profiling_state"
	// PostureSentinelOneRemoteProfilingStateExpiresAt is the datetime field "sentinelone.remote_profiling_state_expires_at". Platforms: windows, macos, linux.
	PostureSentinelOneRemoteProfilingStateExpiresAt PostureTimestampField = "sentinelone.remote_profiling_state_expires_at"
	// PostureSentinelOneScanAbortedAt is the datetime field "sentinelone.scan_aborted_at". Platforms: windows, macos, linux.
	PostureSentinelOneScanAbortedAt PostureTimestampField = "sentinelone.scan_aborted_at"
	// PostureSentinelOneScanFinishedAt is the datetime field "sentinelone.scan_finished_at". Platforms: windows, macos, linux.
	PostureSentinelOneScanFinishedAt PostureTimestampField = "sentinelone.scan_finished_at"
	// PostureSentinelOneScanStartedAt is the datetime field "sentinelone.scan_started_at". Platforms: windows, macos, linux.
	PostureSentinelOneScanStartedAt PostureTimestampField = "sentinelone.scan_started_at"
	// PostureSentinelOneScanStatus is the enum_string field "sentinelone.scan_status". Platforms: windows, macos, linux.
	PostureSentinelOneScanStatus PostureStringField = "sentinelone.scan_status"
	// PostureSentinelOneSentinelOneAccountID is the string field "sentinelone.sentinelone_account_id". Platforms: windows, macos, linux.
	PostureSentinelOneSentinelOneAccountID PostureStringField = "sentinelone.sentinelone_account_id"
	// PostureSentinelOneSentinelOneID is the string field "sentinelone.sentinelone_id". Platforms: windows, macos, linux.
	PostureSentinelOneSentinelOneID PostureStringField = "sentinelone.sentinelone_id"
	// PostureSentinelOneSerialNumber is the string field "sentinelone.serial_number". Platforms: windows, macos, linux.
	PostureSentinelOneSerialNumber PostureStringField = "sentinelone.serial_number"
	// PostureSentinelOneSiteID is the string field "sentinelone.site_id". Platforms: windows, macos, linux.
	PostureSentinelOneSiteID PostureStringField = "sentinelone.site_id"
	// PostureSentinelOneSiteName is the string field "sentinelone.site_name". Platforms: windows, macos, linux.
	PostureSentinelOneSiteName PostureStringField = "sentinelone.site_name"
	// PostureSentinelOneStorageName is the string field "sentinelone.storage_name". Platforms: windows, macos, linux.
	PostureSentinelOneStorageName PostureStringField = "sentinelone.storage_name"
	// PostureSentinelOneStorageType is the string field "sentinelone.storage_type". Platforms: windows, macos, linux.
	PostureSentinelOneStorageType PostureStringField = "sentinelone.storage_type"
	// PostureSentinelOneTags is the json field "sentinelone.tags". Platforms: windows, macos, linux.
	PostureSentinelOneTags PostureJSONField = "sentinelone.tags"
	// PostureSentinelOneThreatRebootRequired is the boolean field "sentinelone.threat_reboot_required". Platforms: windows, macos, linux.
	PostureSentinelOneThreatRebootRequired PostureBoolField = "sentinelone.threat_reboot_required"
	// PostureSentinelOneTotalMemory is the integer field "sentinelone.total_memory". Platforms: windows, macos, linux.
	PostureSentinelOneTotalMemory PostureIntegerField = "sentinelone.total_memory"
	// PostureSentinelOneUserActionsNeeded is the string_array field "sentinelone.user_actions_needed". Platforms: windows, macos, linux.
	PostureSentinelOneUserActionsNeeded PostureStringArrayField = "sentinelone.user_actions_needed"
	// PostureSentinelOneUUID is the string field "sentinelone.uuid". Platforms: windows, macos, linux.
	PostureSentinelOneUUID PostureStringField = "sentinelone.uuid"
)

// Fields of the "sophos" provider.
const (
	// PostureSophosAssignedProducts is the json field "sophos.assigned_products". Platforms: windows, macos, linux.
	PostureSophosAssignedProducts PostureJSONField = "sophos.assigned_products"
	// PostureSophosAssociatedPersonID is the string field "sophos.associated_person_id". Platforms: windows, macos, linux.
	PostureSophosAssociatedPersonID PostureStringField = "sophos.associated_person_id"
	// PostureSophosAssociatedPersonName is the string field "sophos.associated_person_name". Platforms: windows, macos, linux.
	PostureSophosAssociatedPersonName PostureStringField = "sophos.associated_person_name"
	// PostureSophosAssociatedPersonViaLogin is the string field "sophos.associated_person_via_login". Platforms: windows, macos, linux.
	PostureSophosAssociatedPersonViaLogin PostureStringField = "sophos.associated_person_via_login"
	// PostureSophosCloned is the boolean field "sophos.cloned". Platforms: windows, macos, linux.
	PostureSophosCloned PostureBoolField = "sophos.cloned"
	// PostureSophosCloudInstanceID is the string field "sophos.cloud_instance_id". Platforms: windows, macos, linux.
	PostureSophosCloudInstanceID PostureStringField = "sophos.cloud_instance_id"
	// PostureSophosCloudProvider is the enum_string field "sophos.cloud_provider". Platforms: windows, macos, linux.
	PostureSophosCloudProvider PostureStringField = "sophos.cloud_provider"
	// PostureSophosDeviceSoftware is the json field "sophos.device_software". Platforms: windows, macos, linux.
	PostureSophosDeviceSoftware PostureJSONField = "sophos.device_software"
	// PostureSophosEncryptionOverallStatus is the enum_string field "sophos.encryption_overall_status". Platforms: windows, macos, linux.
	PostureSophosEncryptionOverallStatus PostureStringField = "sophos.encryption_overall_status"
	// PostureSophosEncryptionVolumes is the json field "sophos.encryption_volumes". Platforms: windows, macos, linux.
	PostureSophosEncryptionVolumes PostureJSONField = "sophos.encryption_volumes"
	// PostureSophosEnrolled is the boolean field "sophos.enrolled". Platforms: windows, macos, linux.
	PostureSophosEnrolled PostureBoolField = "sophos.enrolled"
	// PostureSophosGroupHierarchy is the json field "sophos.group_hierarchy". Platforms: windows, macos, linux.
	PostureSophosGroupHierarchy PostureJSONField = "sophos.group_hierarchy"
	// PostureSophosGroupID is the string field "sophos.group_id". Platforms: windows, macos, linux.
	PostureSophosGroupID PostureStringField = "sophos.group_id"
	// PostureSophosGroupName is the string field "sophos.group_name". Platforms: windows, macos, linux.
	PostureSophosGroupName PostureStringField = "sophos.group_name"
	// PostureSophosHealthOverall is the enum_string field "sophos.health_overall". Platforms: windows, macos, linux.
	PostureSophosHealthOverall PostureStringField = "sophos.health_overall"
	// PostureSophosHealthServiceDetails is the json field "sophos.health_service_details". Platforms: windows, macos, linux.
	PostureSophosHealthServiceDetails PostureJSONField = "sophos.health_service_details"
	// PostureSophosHealthServicesStatus is the enum_string field "sophos.health_services_status". Platforms: windows, macos, linux.
	PostureSophosHealthServicesStatus PostureStringField = "sophos.health_services_status"
	// PostureSophosHealthThreatsStatus is the enum_string field "sophos.health_threats_status". Platforms: windows, macos, linux.
	PostureSophosHealthThreatsStatus PostureStringField = "sophos.health_threats_status"
	// PostureSophosHostname is the string field "sophos.hostname". Platforms: windows, macos, linux.
	PostureSophosHostname PostureStringField = "sophos.hostname"
	// PostureSophosIPv4Addresses is the string_array field "sophos.ipv4_addresses". Platforms: windows, macos, linux.
	PostureSophosIPv4Addresses PostureStringArrayField = "sophos.ipv4_addresses"
	// PostureSophosIPv6Addresses is the string_array field "sophos.ipv6_addresses". Platforms: windows, macos, linux.
	PostureSophosIPv6Addresses PostureStringArrayField = "sophos.ipv6_addresses"
	// PostureSophosIsolationAdminIsolated is the boolean field "sophos.isolation_admin_isolated". Platforms: windows, macos, linux.
	PostureSophosIsolationAdminIsolated PostureBoolField = "sophos.isolation_admin_isolated"
	// PostureSophosIsolationSelfIsolated is the boolean field "sophos.isolation_self_isolated". Platforms: windows, macos, linux.
	PostureSophosIsolationSelfIsolated PostureBoolField = "sophos.isolation_self_isolated"
	// PostureSophosIsolationStatus is the enum_string field "sophos.isolation_status". Platforms: windows, macos, linux.
	PostureSophosIsolationStatus PostureStringField = "sophos.isolation_status"
	// PostureSophosLastAgentUpdateAt is the datetime field "sophos.last_agent_update_at". Platforms: windows, macos, linux.
	PostureSophosLastAgentUpdateAt PostureTimestampField = "sophos.last_agent_update_at"
	// PostureSophosLastOSUpdateAt is the datetime field "sophos.last_os_update_at". Platforms: windows, macos, linux.
	PostureSophosLastOSUpdateAt PostureTimestampField = "sophos.last_os_update_at"
	// PostureSophosLastSeenAt is the datetime field "sophos.last_seen_at". Platforms: windows, macos, linux.
	PostureSophosLastSeenAt PostureTimestampField = "sophos.last_seen_at"
	// PostureSophosLockdownStatus is the enum_string field "sophos.lockdown_status". Platforms: windows, macos, linux.
	PostureSophosLockdownStatus PostureStringField = "sophos.lockdown_status"
	// PostureSophosMACAddresses is the string_array field "sophos.mac_addresses". Platforms: windows, macos, linux.
	PostureSophosMACAddresses PostureStringArrayField = "sophos.mac_addresses"
	// PostureSophosOnline is the boolean field "sophos.online". Platforms: windows, macos, linux.
	PostureSophosOnline PostureBoolField = "sophos.online"
	// PostureSophosOSBuild is the integer field "sophos.os_build". Platforms: windows, macos, linux.
	PostureSophosOSBuild PostureIntegerField = "sophos.os_build"
	// PostureSophosOSIsServer is the boolean field "sophos.os_is_server". Platforms: windows, macos, linux.
	PostureSophosOSIsServer PostureBoolField = "sophos.os_is_server"
	// PostureSophosOSMajorVersion is the integer field "sophos.os_major_version". Platforms: windows, macos, linux.
	PostureSophosOSMajorVersion PostureIntegerField = "sophos.os_major_version"
	// PostureSophosOSMinorVersion is the integer field "sophos.os_minor_version". Platforms: windows, macos, linux.
	PostureSophosOSMinorVersion PostureIntegerField = "sophos.os_minor_version"
	// PostureSophosOSName is the string field "sophos.os_name". Platforms: windows, macos, linux.
	PostureSophosOSName PostureStringField = "sophos.os_name"
	// PostureSophosOSPlatform is the enum_string field "sophos.os_platform". Platforms: windows, macos, linux.
	PostureSophosOSPlatform PostureStringField = "sophos.os_platform"
	// PostureSophosOSUpToDate is the boolean field "sophos.os_up_to_date". Platforms: macos.
	PostureSophosOSUpToDate PostureBoolField = "sophos.os_up_to_date"
	// PostureSophosPackages is the json field "sophos.packages". Platforms: windows, macos, linux.
	PostureSophosPackages PostureJSONField = "sophos.packages"
	// PostureSophosSerialNumber is the string field "sophos.serial_number". Platforms: windows, macos, linux.
	PostureSophosSerialNumber PostureStringField = "sophos.serial_number"
	// PostureSophosSophosID is the string field "sophos.sophos_id". Platforms: windows, macos, linux.
	PostureSophosSophosID PostureStringField = "sophos.sophos_id"
	// PostureSophosTags is the json field "sophos.tags". Platforms: windows, macos, linux.
	PostureSophosTags PostureJSONField = "sophos.tags"
	// PostureSophosTamperProtectionEnabled is the boolean field "sophos.tamper_protection_enabled". Platforms: windows, macos, linux.
	PostureSophosTamperProtectionEnabled PostureBoolField = "sophos.tamper_protection_enabled"
	// PostureSophosTamperProtectionSupported is the boolean field "sophos.tamper_protection_supported". Platforms: windows, macos, linux.
	PostureSophosTamperProtectionSupported PostureBoolField = "sophos.tamper_protection_supported"
	// PostureSophosType is the enum_string field "sophos.type". Platforms: windows, macos, linux.
	PostureSophosType PostureStringField = "sophos.type"
)
